# URL de la base de datos
db.url=jdbc:mysql://localhost:3306/gestion_compras?useSSL=false

# Usuario 1
db.admin=admin
db.passwordadmin=admin123

# Usuario 2
db.usercontable=contable
db.passwordcontable=contable123

# Usuario 3
db.userjefe=jefe_dep
db.passwordjefe=jefe123

# Usuario 4
db.userwebapp=webapp
db.passwordwebapp=webapp